BookStoreMvcWeb/Models/CartIndextViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using BookStoreMvcWeb.Domain.Entities;

namespace BookStoreMvcWeb.Models 
{
    public class CartIndextViewModel
    {
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
    }
}

BookStoreMvcWeb/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;


namespace BookStoreMvcWeb.Models
{
    public class LoginViewModel
    {
        [Required]
        [Display(Name="Nazwa użytkownika")]
        public string UserName { get; set; }

        [Required]
        [Display(Name="Hasło")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

BookStoreMvcWeb/Models/PageInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BookStoreMvcWeb.Models
{
    public class PageInfo
    {
        public int TotalItems { get; set; }
        public int ItemsPerPage { get; set; }
        public int CurrentPage { get; set; }
        public int TotalPage { get { return (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage); } }
    }
}

BookStoreMvcWeb/Models/ProductListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using BookStoreMvcWeb.Domain.Entities;
using BookStoreMvcWeb.Models;

namespace BookStoreMvcWeb.Models
{
    public class ProductListViewModel
    {
        public IEnumerable<Product> Products { get; set; }
        public PageInfo PageInfo { get; set; }
        public string CurrentCategory { get; set; }
    }
}

BookStoreMvcWeb/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookStoreMvcWeb.Domain.Abstract;
using BookStoreMvcWeb.Domain.Concrete;
using BookStoreMvcWeb.Infrastructure.Concrete;
using BookStoreMvcWeb.Models;

namespace BookStoreMvcWeb.Controllers
{
    public class AccountController : Controller
    {
        IAuthProvider AuthProvider;

        public AccountController(IAuthProvider AuthProvider)
        {
            this.AuthProvider = AuthProvider;
        }


        public ViewResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginViewModel model, string returnUrl)
        {
            if (ModelState.IsValid)
                if (AuthProvider.Authenticate(model.UserName, model.Password))
                {
                    return Redirect(returnUrl ?? Url.Action("Index", "Admin"));
                }
                else{
                    ModelState.AddModelError("", "Nieprawidłowa nazwa użytkownika lub niepoprawne hasło");
                        return View();
                }
            else return View();
        }
    }
}

BookStoreMvcWeb/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookStoreMvcWeb.Models;
using BookStoreMvcWeb.Domain.Entities;
using BookStoreMvcWeb.Domain.Abstract;
using BookStoreMvcWeb.Domain.Concrete;

namespace BookStoreMvcWeb.Controllers
{

    [Authorize]
    public class AdminController : Controller
    {
        private IProductRepository repository {get; set;}
        public AdminController(IProductRepository repository)
        {
            this.repository=repository;
        }
       public ViewResult Index()
       {
           return View(repository.Products);
       }
       public ViewResult Edit(int ProductId)
       {
           Product product = repository.Products
               .FirstOrDefault(x => x.ProductID == ProductId);
           return View(product);
       }
        [HttpPost]
        public ActionResult Edit(Product product)
       {
           if (ModelState.IsValid)
           {
               repository.SaveProduct(product);
               return RedirectToAction("Index");
           }
           else return View(product);
       }
    }
}

BookStoreMvcWeb/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookStoreMvcWeb.Models;
using BookStoreMvcWeb.Domain.Entities;
using BookStoreMvcWeb.Domain.Abstract;
using BookStoreMvcWeb.Domain.Concrete;

namespace BookStoreMvcWeb.Controllers
{
    public class CartController : Controller
    {
        private IProductRepository repository;
        public CartController(IProductRepository repository)
        {
            this.repository = repository;
        }
        public RedirectToRouteResult AddToCart(Cart cart, int productID, string returnUrl)
        {
            Product product = repository.Products
                .FirstOrDefault(e => e.ProductID == productID);
            if(product!=null)
            {
                cart.AddItem(product, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int productID, string returnUrl)
        {
            Product product = repository.Products
                .FirstOrDefault(x => x.ProductID == productID);

            if (product != null) cart.RemoveLine(product);
            return RedirectToAction("Index", new { returnUrl });
        }

        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }

        [HttpPost]
        public ViewResult Checkout(ShippingDetails shiping)
        {
            return View("ShipingDetailsSummary", shiping);
        }
        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndextViewModel
                {
                    Cart = cart,
                    ReturnUrl = returnUrl
                });
        }
    }
}

BookStoreMvcWeb/Controllers/NavigationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookStoreMvcWeb.Domain.Abstract;

namespace BookStoreMvcWeb.Controllers
{
    public class NavigationController : Controller
    {
        private IProductRepository repository;

        public NavigationController(IProductRepository repository)
        {
            this.repository = repository;
        }
        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;
            IEnumerable<string> categories = repository.Products
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);
            return PartialView(categories);
        }

    }
}

BookStoreMvcWeb/Controllers/ProductController.cs
using BookStoreMvcWeb.Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookStoreMvcWeb.Models;

namespace BookStoreMvcWeb.Controllers
{
    public class ProductController : Controller
    {
        private IProductRepository repository;
        public int PageSize = 4;

        public ProductController(IProductRepository repository)
        {
            this.repository = repository;
        }
        public ViewResult Index(string category, int page = 1)
        {
            ProductListViewModel viewModel = new ProductListViewModel
            {
                Products = repository.Products
                .Where(p => category == null ? true : p.Category == category)
                .OrderBy(x => x.ProductID)
                .Skip((page - 1) * PageSize)
                .Take(PageSize),
                PageInfo = new PageInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = category == null ? repository.Products.Count() :
                    repository.Products.Where(e => e.Category == category).Count()
                },
                CurrentCategory = category
            };
            return View(viewModel);
        }

    }
}

BookStoreMvcWeb/Views/Admin/Edit.cshtml
@model BookStoreMvcWeb.Domain.Entities.Product

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminView.cshtml";
}
<div class="container">
    <h2>Edit @Model.Name</h2>
    @using (Html.BeginForm("Edit", "Admin"))
    {
        @Html.ValidationSummary();
        <form class="form-horizontal">
            <div class="form-group">
                @Html.LabelFor(x => x.Name, new { @class = "col-sm-2 control-label" })
                <div class="col-sm-10">
                    @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(x => x.Author, new { @class = "col-sm-2 control-label" })
                    <div class="col-sm-10">
                        @Html.TextBoxFor(x => x.Author, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(x => x.Category, new { @class = "col-sm-2 control-label" })
                        <div class="col-sm-10">
                            @Html.TextBoxFor(x => x.Category, new { @class = "form-control" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(x => x.Description, new { @class = "col-sm-2 control-label" })
                            <div class="col-sm-10">
                                @Html.TextAreaFor(x => x.Description, 5, 10, new { @class = "form-control" })
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <input type="submit" class="btn btn-success" value="Zapisz" />
        </form>
    }
</div>

BookStoreMvcWeb/Views/Admin/Index.cshtml
@model IEnumerable<BookStoreMvcWeb.Domain.Entities.Product>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminView.cshtml";
}
<div class="container">
    <h2>Panel administracyjny</h2>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table table-condensed">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Author)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Author)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Category)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { ProductId = item.ProductID }) |
                    @Html.ActionLink("Details", "Details", new { ProductId = item.ProductID }) |
                    @Html.ActionLink("Delete", "Delete", new { ProductId = item.ProductID })
                </td>
            </tr>
        }
    </table>
</div>

BookStoreMvcWeb/Views/Cart/Checkout.cshtml
@model BookStoreMvcWeb.Domain.Entities.ShippingDetails

@{
    ViewBag.Title = "Checkout";
}

<h2>Checkout</h2>
@using(Html.BeginForm())
{
    <h3>Wysyłka dla: </h3>
    <form class="form-inline">
        <div class="form-group">
            <label>Imię</label>
           @Html.TextBoxFor(x => x.FirstName, new { @class="form-control", placeholder = "joe"})
            </div>
        <div class="form-group">
            <label>Nazwisko</label>
            @Html.TextBoxFor(x => x.LastName, new { @class = "form-control" })
        </div>
        <div class="form-group">
            <label>Ulica</label>
            @Html.TextBoxFor(x => x.StreetAdress, new { @class = "form-control" })
        </div>
        <div class="form-group">
            <label>Miasto</label>
            @Html.TextBoxFor(x => x.City, new { @class = "form-control" })
        </div>
        <div class="form-group">
            <label>Kraj</label>
            @Html.TextBoxFor(x => x.Country, new { @class = "form-control" })
        </div>
        <input type="submit" value="Utwórz" />
    </form>
}

BookStoreMvcWeb/Views/Cart/Index.cshtml
@model BookStoreMvcWeb.Models.CartIndextViewModel

@{
    ViewBag.Title = "Twój koszyk";
}
<h2 class="h2">Twój koszyk</h2>
<div class="container">
    <div class="row">
        <div class="col-xs-2">
        </div>
        <div class="col-xs-6">
            <h3 class="h3">Nazwa produktu</h3>
        </div>
        <div class="col-xs-2">
            <h3>Ilość</h3>
        </div>
        <div class="col-xs-2"><h3>Cena</h3></div>
    </div>
    <div class="row">
        <div class="col-xs-2">@{Html.RenderAction("Menu", "Navigation");}</div>
        @foreach (var p in Model.Cart.Lines)
        {
            <div class="col-xs-6">
                <h3 class="h3">@p.Product.Name</h3>
            </div>
            <div class="col-xs-1">
                <h3>@p.Quantity</h3>
            </div>
            <div class="col-xs-2"><h3>@((p.Product.Price * p.Quantity).ToString("c"))</h3></div>
            <div class="col-xs-1">
                @using (Html.BeginForm("RemoveFromCart", "Cart"))
                {
                    @Html.Hidden("ProductId", p.Product.ProductID)
                    @Html.HiddenFor(x => x.ReturnUrl)
                    <input class="btn btn-warning" type="submit" value="usun" />
                }
            </div>
        }
    </div>
    <div class="row">
        <div class="col-xs-2"></div>
        <div class="col-xs-6">
            <p>
                <a href="@Model.ReturnUrl" class="btn btn-default" role="button">Kontynuuj zakupy</a>
                @Html.ActionLink("Order", "Checkout")
            </p>
        </div>
        <div class="col-xs-2">
            <h3>Razem</h3>
        </div>
        <div class="col-xs-2"><h3>@Model.Cart.ComputeTotalValue().ToString("c")</h3></div>
    </div>
</div>

BookStoreMvcWeb/Views/Cart/ShipingDetailsSummary.cshtml
@model BookStoreMvcWeb.Domain.Entities.ShippingDetails

@{
    ViewBag.Title = "ShipingDetailsSummary";
}

<h2>Dane do wysyłki - podsumowanie</h2>

<address>
    <strong>@Model.FirstName, @Model.LastName</strong><br />
</address>

BookStoreMvcWeb/Views/Navigation/Menu.cshtml
@model IEnumerable<string>

<p>@Html.ActionLink("Home", "Index", "Product")</p>
@foreach (var link in Model)
{
   <p>@Html.RouteLink(link, new { controller = "Product", action = "Index", category = link, page = 1 })</p>
}

BookStoreMvcWeb/Views/Product/Index.cshtml
@model BookStoreMvcWeb.Models.ProductListViewModel
@{
    ViewBag.Title = "Index";
}
<div class="container">
<div class="row" >
    <div class="col-xs-2">
        @{Html.RenderAction("Menu", "Navigation");}
    </div>
    <div class="col-xs-8">
        @foreach (var p in Model.Products)
        {
        Html.RenderPartial("ProductSummary", p);
        }
        </div>
    </div>
    <div class="row">
        <div class="pager">
            @Html.PageLinks(Model.PageInfo, x => Url.Action("Index", new { page = x, category = Model.CurrentCategory }))
        </div>
    </div>
</div>

BookStoreMvcWeb/Views/Shared/ProductSummary.cshtml
@model BookStoreMvcWeb.Domain.Entities.Product

<h3>@Model.Name</h3>
@Model.Description
@using (Html.BeginForm("AddToCart", "Cart"))
{
    @Html.HiddenFor(x => x.ProductID)
    @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
    <input type="submit" value="+dodaj do koszyka" />
}
<h4>@Model.Price.ToString("c")</h4>

BookStoreMvcWeb/Views/Shared/_AdminView.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Admin View</title>   
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div>   
        @RenderBody();
</div>
</body>
</html>

BookStoreMvcWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>Strona</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet"/>
    
</head>
<body>
    <div class="container">   
        <nav class="navbar navbar-inverse">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Home", "Index", "Product", new { @class = "navbar-brand" })        
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
                        <li><a href="#">Link</a></li>
                        </ul>
                    <form class="navbar-form navbar-left" role="search">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Szukaj">
                        </div>
                        <button type="submit" class="btn btn-default">Szukaj produktu</button>
                    </form>    
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <blockquote class="blockquote-reverse">
                    <p>Skończ z byciem wielbłądem, przejmij inicjatywe i stań się lwem!</p>
                    <footer>Friedrich Nietzsche</footer>
                </blockquote>
            </div>
        </div>
    @RenderBody()
</body>
</html>